### ISSUE TITLE
Getting FileNotFoundError: [Errno 2] No such file or directory: 'Figures/AAPL_Rendering.png'

### ISSUE THREAD

**Issue by Athe-kunal** [ThibautTheate/An-Application-of-Deep-Reinforcement-Learning-to-Algorithmic-Trading#1]
I tried running the code on google colab with cuda enabled gpu. I am attaching the traceback here. Do I need to create a file manually? 

Traceback (most recent call last):
  File "main.py", line 37, in <module>
    simulator.simulateNewStrategy(strategy, stock, saveStrategy=False)
  File "/content/An-Application-of-Deep-Reinforcement-Learning-to-Algorithmic-Trading/tradingSimulator.py", line 421, in simulateNewStrategy
    plotTraining=plotTraining, showPerformance=showPerformance)
  File "/content/An-Application-of-Deep-Reinforcement-Learning-to-Algorithmic-Trading/TDQN.py", line 757, in training
    trainingEnv.render()
  File "/content/An-Application-of-Deep-Reinforcement-Learning-to-Algorithmic-Trading/tradingEnv.py", line 399, in render
    plt.savefig(''.join(['Figures/', str(self.marketSymbol), '_Rendering', '.png']))
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py", line 723, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/figure.py", line 2203, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backend_bases.py", line 2126, in print_figure
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_agg.py", line 535, in print_png
    with cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/cbook/__init__.py", line 418, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/cbook/__init__.py", line 403, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'Figures/AAPL_Rendering.png'

**Comment by ThibautTheate** [comment]
The code was double-checked and successfully run on a local machine equipped with GPU.  I am not really familiar with Google Colab, but I am pretty sure that the error comes from the integration of the code into Google Colab. There is no need to create a file manually, but did you check that there is a valid access to the required location (“Figures” folder)?

**Comment by Athe-kunal** [comment]
Yes I had changed my current working directory to the required directory of "An Application of ...". But will run on a local machine and check it again.
Thanks
